"""
    MetaSV API Spec

    API definition for MetaSV provided apis  # noqa: E501

    The version of the OpenAPI document: 2.2.0
    Contact: heqiming@metasv.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import metasv_mvc_client
from metasv_mvc_client.api.xpub_api import XpubApi  # noqa: E501


class TestXpubApi(unittest.TestCase):
    """XpubApi unit test stubs"""

    def setUp(self):
        self.api = XpubApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_xpub_lite_xpub_address_address_get(self):
        """Test case for xpub_lite_xpub_address_address_get

        Get xpub address type and index. Only index under /0/70 /1/30 is valid. Otherwise not found.  # noqa: E501
        """
        pass

    def test_xpub_lite_xpub_balance_get(self):
        """Test case for xpub_lite_xpub_balance_get

        Get xpub balances including confirmed and unconfirmed.  # noqa: E501
        """
        pass

    def test_xpub_lite_xpub_utxo_get(self):
        """Test case for xpub_lite_xpub_utxo_get

        Get xpub utxos by specific xpub(300 per page).  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
