"""
    MicrovisionChain API Document

    API definition for MicrovisionChain provided apis  # noqa: E501

    The version of the OpenAPI document: 3.0.8
    Contact: heqiming@mvcapi.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import mvcapi-sdk
from mvcapi-sdk.model.block_tx import BlockTx
from mvcapi-sdk.model.tx_input import TxInput
from mvcapi-sdk.model.tx_output import TxOutput
globals()['BlockTx'] = BlockTx
globals()['TxInput'] = TxInput
globals()['TxOutput'] = TxOutput
from mvcapi-sdk.model.tx_detail import TxDetail


class TestTxDetail(unittest.TestCase):
    """TxDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTxDetail(self):
        """Test TxDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TxDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
