"""
    MetaSV API Spec

    API definition for MetaSV provided apis  # noqa: E501

    The version of the OpenAPI document: 2.2.0
    Contact: heqiming@metasv.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import metasv_mvc_client
from metasv_mvc_client.api.merchant_api import MerchantApi  # noqa: E501


class TestMerchantApi(unittest.TestCase):
    """MerchantApi unit test stubs"""

    def setUp(self):
        self.api = MerchantApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_merchant_utxo_post(self):
        """Test case for merchant_utxo_post

        Pick utxos by addresses and amount.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
