"""
    MicrovisionChain API Document

    API definition for MicrovisionChain provided apis  # noqa: E501

    The version of the OpenAPI document: 3.0.8
    Contact: heqiming@mvcapi.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import mvcapi-sdk
from mvcapi-sdk.model.invalid_broadcast_collide import InvalidBroadcastCollide
globals()['InvalidBroadcastCollide'] = InvalidBroadcastCollide
from mvcapi-sdk.model.invalid_broad_cast import InvalidBroadCast


class TestInvalidBroadCast(unittest.TestCase):
    """InvalidBroadCast unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInvalidBroadCast(self):
        """Test InvalidBroadCast"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InvalidBroadCast()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
