"""
    MetaSV API Spec

    API definition for MetaSV provided apis  # noqa: E501

    The version of the OpenAPI document: 2.2.0
    Contact: heqiming@metasv.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import metasv_mvc_client
from metasv_mvc_client.model.block_tx import BlockTx
from metasv_mvc_client.model.tx_input import TxInput
from metasv_mvc_client.model.tx_output import TxOutput
globals()['BlockTx'] = BlockTx
globals()['TxInput'] = TxInput
globals()['TxOutput'] = TxOutput
from metasv_mvc_client.model.tx_detail import TxDetail


class TestTxDetail(unittest.TestCase):
    """TxDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTxDetail(self):
        """Test TxDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TxDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
