"""
    MetaSV API Spec

    API definition for MetaSV provided apis  # noqa: E501

    The version of the OpenAPI document: 2.2.0
    Contact: heqiming@metasv.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import metasv_mvc_client
from metasv_mvc_client.api.block_api import BlockApi  # noqa: E501


class TestBlockApi(unittest.TestCase):
    """BlockApi unit test stubs"""

    def setUp(self):
        self.api = BlockApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_block_block_id_get(self):
        """Test case for block_block_id_get

        Get block request by height or hash  # noqa: E501
        """
        pass

    def test_block_get(self):
        """Test case for block_get

        Get recent block list by paging. 30 items per page.  # noqa: E501
        """
        pass

    def test_block_info_get(self):
        """Test case for block_info_get

        Get current blockchain info from full node.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
