"""
    MicrovisionChain API Document

    API definition for MicrovisionChain provided apis  # noqa: E501

    The version of the OpenAPI document: 3.0.8
    Contact: heqiming@mvcapi.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import mvcapi-sdk
from mvcapi-sdk.api.block_api import BlockApi  # noqa: E501


class TestBlockApi(unittest.TestCase):
    """BlockApi unit test stubs"""

    def setUp(self):
        self.api = BlockApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_block_block_id_get(self):
        """Test case for block_block_id_get

        Get block request by height or hash  # noqa: E501
        """
        pass

    def test_block_get(self):
        """Test case for block_get

        Get recent block list by paging. 30 items per page.  # noqa: E501
        """
        pass

    def test_block_info_get(self):
        """Test case for block_info_get

        Get current blockchain info from full node.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
