"""
    MicrovisionChain API Document

    API definition for MicrovisionChain provided apis  # noqa: E501

    The version of the OpenAPI document: 3.0.8
    Contact: heqiming@mvcapi.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import mvcapi-sdk
from mvcapi-sdk.model.contract_nft_sell_v2_utxo import ContractNftSellV2Utxo


class TestContractNftSellV2Utxo(unittest.TestCase):
    """ContractNftSellV2Utxo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContractNftSellV2Utxo(self):
        """Test ContractNftSellV2Utxo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ContractNftSellV2Utxo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
