"""
    MicrovisionChain API Document

    API definition for MicrovisionChain provided apis  # noqa: E501

    The version of the OpenAPI document: 3.0.8
    Contact: heqiming@mvcapi.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import mvcapi-sdk
from mvcapi-sdk.api.treasury_api import TreasuryApi  # noqa: E501


class TestTreasuryApi(unittest.TestCase):
    """TreasuryApi unit test stubs"""

    def setUp(self):
        self.api = TreasuryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_treasury_get(self):
        """Test case for treasury_get

        Get current treasury info.  # noqa: E501
        """
        pass

    def test_treasury_history_get(self):
        """Test case for treasury_history_get

        Get all treasury history.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
