"""
    MicrovisionChain API Document

    API definition for MicrovisionChain provided apis  # noqa: E501

    The version of the OpenAPI document: 3.0.8
    Contact: heqiming@mvcapi.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import mvcapi-sdk
from mvcapi-sdk.api.contract_api import ContractApi  # noqa: E501


class TestContractApi(unittest.TestCase):
    """ContractApi unit test stubs"""

    def setUp(self):
        self.api = ContractApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_contract_ft_address_address_balance_confirmed_get(self):
        """Test case for contract_ft_address_address_balance_confirmed_get

        Get all contract token balances for specific address ignoring all unconfirmed txs.  # noqa: E501
        """
        pass

    def test_contract_ft_address_address_balance_get(self):
        """Test case for contract_ft_address_address_balance_get

        Get all contract token balances for specific address.  # noqa: E501
        """
        pass

    def test_contract_ft_address_address_code_hash_genesis_tx_get(self):
        """Test case for contract_ft_address_address_code_hash_genesis_tx_get

        Get all contract token balances for specific address.  # noqa: E501
        """
        pass

    def test_contract_ft_address_address_utxo_get(self):
        """Test case for contract_ft_address_address_utxo_get

        Get all contract token utxos for specific address.  # noqa: E501
        """
        pass

    def test_contract_nft_address_address_count_confirmed_get(self):
        """Test case for contract_nft_address_address_count_confirmed_get

        Get confirmed utxo count for specific nft(ignore all unconfirmed txs).  # noqa: E501
        """
        pass

    def test_contract_nft_address_address_summary_get(self):
        """Test case for contract_nft_address_address_summary_get

        Get nft summary(NFT count group by genesis) for address.  # noqa: E501
        """
        pass

    def test_contract_nft_address_address_utxo_get(self):
        """Test case for contract_nft_address_address_utxo_get

        Get all contract nft token utxos for specific address.  # noqa: E501
        """
        pass

    def test_contract_nft_genesis_code_hash_genesis_summary_get(self):
        """Test case for contract_nft_genesis_code_hash_genesis_summary_get

        Get nft summary(count group by address) for specific codeHash and genesisId(result cached for 60s).  # noqa: E501
        """
        pass

    def test_contract_nft_genesis_code_hash_genesis_utxo_get(self):
        """Test case for contract_nft_genesis_code_hash_genesis_utxo_get

        Get all contract nft token utxos by codeHash and genesisId.  # noqa: E501
        """
        pass

    def test_contract_nft_sell_address_address_utxo_get(self):
        """Test case for contract_nft_sell_address_address_utxo_get

        Get all contract sell sell utxos for specific address.  # noqa: E501
        """
        pass

    def test_contract_nft_sell_genesis_code_hash_genesis_utxo_get(self):
        """Test case for contract_nft_sell_genesis_code_hash_genesis_utxo_get

        Get all contract nft token utxos by codeHash and genesisId.  # noqa: E501
        """
        pass

    def test_contract_unique_genesis_code_hash_genesis_utxo_get(self):
        """Test case for contract_unique_genesis_code_hash_genesis_utxo_get

        Get contract unique utxos by codeHash and genesisId.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
