"""
    MicrovisionChain API Document

    API definition for MicrovisionChain provided apis  # noqa: E501

    The version of the OpenAPI document: 3.0.8
    Contact: heqiming@mvcapi.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import mvcapi-sdk
from mvcapi-sdk.model.block_header_index import BlockHeaderIndex


class TestBlockHeaderIndex(unittest.TestCase):
    """BlockHeaderIndex unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlockHeaderIndex(self):
        """Test BlockHeaderIndex"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BlockHeaderIndex()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
