"""
    MetaSV API Spec

    API definition for MetaSV provided apis  # noqa: E501

    The version of the OpenAPI document: 2.2.0
    Contact: heqiming@metasv.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import metasv_mvc_client
from metasv_mvc_client.model.xpub_address import XpubAddress


class TestXpubAddress(unittest.TestCase):
    """XpubAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testXpubAddress(self):
        """Test XpubAddress"""
        # FIXME: construct object with mandatory attributes with example values
        # model = XpubAddress()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
