"""
    MicrovisionChain API Document

    API definition for MicrovisionChain provided apis  # noqa: E501

    The version of the OpenAPI document: 3.0.8
    Contact: heqiming@mvcapi.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

import nulltype  # noqa: F401

from mvcapi-sdk.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)


class ContractNftSellV2Utxo(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'address': (str,),  # noqa: E501
            'contract_address': (str,),  # noqa: E501
            'txid': (str,),  # noqa: E501
            'tx_index': (int,),  # noqa: E501
            'code_hash': (str,),  # noqa: E501
            'genesis': (str,),  # noqa: E501
            'token_index': (int,),  # noqa: E501
            'price': (int,),  # noqa: E501
            'fee_address_pkh': (str,),  # noqa: E501
            'fee_rate': (int,),  # noqa: E501
            'nft_id': (str,),  # noqa: E501
            'seller_address_pkh': (str,),  # noqa: E501
            'satoshi': (int,),  # noqa: E501
            'satoshi_string': (str,),  # noqa: E501
            'height': (int,),  # noqa: E501
            'is_ready': (bool,),  # noqa: E501
            'sensible_id': (str,),  # noqa: E501
            'meta_txid': (str,),  # noqa: E501
            'meta_output_index': (int,),  # noqa: E501
            'token_supply': (int,),  # noqa: E501
            'flag': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'address': 'address',  # noqa: E501
        'contract_address': 'contractAddress',  # noqa: E501
        'txid': 'txid',  # noqa: E501
        'tx_index': 'txIndex',  # noqa: E501
        'code_hash': 'codeHash',  # noqa: E501
        'genesis': 'genesis',  # noqa: E501
        'token_index': 'tokenIndex',  # noqa: E501
        'price': 'price',  # noqa: E501
        'fee_address_pkh': 'feeAddressPkh',  # noqa: E501
        'fee_rate': 'feeRate',  # noqa: E501
        'nft_id': 'nftId',  # noqa: E501
        'seller_address_pkh': 'sellerAddressPkh',  # noqa: E501
        'satoshi': 'satoshi',  # noqa: E501
        'satoshi_string': 'satoshiString',  # noqa: E501
        'height': 'height',  # noqa: E501
        'is_ready': 'isReady',  # noqa: E501
        'sensible_id': 'sensibleId',  # noqa: E501
        'meta_txid': 'metaTxid',  # noqa: E501
        'meta_output_index': 'metaOutputIndex',  # noqa: E501
        'token_supply': 'tokenSupply',  # noqa: E501
        'flag': 'flag',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """ContractNftSellV2Utxo - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            address (str): Address string of this utxo. [optional]  # noqa: E501
            contract_address (str): Address calculated from contract hash(p2ch).. [optional]  # noqa: E501
            txid (str): Txid for this utxo.. [optional]  # noqa: E501
            tx_index (int): Output index for the Utxo.. [optional]  # noqa: E501
            code_hash (str): Codehash of this utxo.. [optional]  # noqa: E501
            genesis (str): Genesis of this utxo.. [optional]  # noqa: E501
            token_index (int): The index of this NFT.. [optional]  # noqa: E501
            price (int): the price of nft.. [optional]  # noqa: E501
            fee_address_pkh (str): The address to receive fees.. [optional]  # noqa: E501
            fee_rate (int): feeRate. [optional]  # noqa: E501
            nft_id (str): nftId. [optional]  # noqa: E501
            seller_address_pkh (str): The address pkh of seller. [optional]  # noqa: E501
            satoshi (int): Mvc value of the utxo(Irrelavant to token value). [optional]  # noqa: E501
            satoshi_string (str): Mvc value of the utxo(In string format). [optional]  # noqa: E501
            height (int): The height of this utxo, -1 for unconfirmed utxo.. [optional]  # noqa: E501
            is_ready (bool): Is current nft transfered into sell contract, If not ready, the following fields will be null. [optional]  # noqa: E501
            sensible_id (str): SensibleId of the token. [optional]  # noqa: E501
            meta_txid (str): The metanet tx describing the nft.. [optional]  # noqa: E501
            meta_output_index (int): Symbol of the token.. [optional]  # noqa: E501
            token_supply (int): The total supply of this NFT.. [optional]  # noqa: E501
            flag (str): Flag used for paging. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
